FROM maven:3.9-eclipse-temurin-17 AS build
WORKDIR /app

COPY app/spring-boot-server/pom.xml .
RUN mvn dependency:go-offline -B

COPY app/spring-boot-server/src ./src
RUN mvn clean package -DskipTests -B

FROM eclipse-temurin:17-jre-alpine
WORKDIR /opt/app

COPY --from=build /app/target/*.jar app.jar

ENTRYPOINT ["java", "-jar", "app.jar"]