FROM node:24-alpine AS build
WORKDIR /app

COPY app/angular-17-client/package*.json ./
RUN npm ci

COPY app/angular-17-client/ .
RUN npm run build

FROM nginx:alpine
RUN rm -rf /usr/share/nginx/html/*
COPY --from=build /app/dist/angular-17-crud/browser/* /usr/share/nginx/html/

COPY default.conf /etc/nginx/conf.d/default.conf